In [38]:
# All numbers which are divisible by 7 but are not a multiple of 5 between 2000 and 3200
def divSevenNotMulFive (minBound, maxBound):
    result =[ ]
    for num in range(minBound, maxBound+1):
        if((num % 5 !=0 ) & (num % 7 == 0)):
            result.append(num)
    print("The number of numbers divisible by 7 and not multiple of 5 between ",minBound," and ",maxBound," is: ", len(result))        
    print(result)

In [39]:
divSevenNotMulFive(2000,3200)

The number of numbers divisible by 7 and not multiple of 5 between  2000  and  3200  is:  138
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [41]:
# Factorial of a given number n

def Facto (n):
    if ((n == 0) | (n== 1) ):
        return 1
    else:
        return n* Facto(n-1)

In [42]:
controle= False 
while(controle != True):
    try:
        n=int(input("Enter an integer number: "))
        print(Facto(n))
        controle = True        
    except ValueError:
        print("Please input integer only...") 


Enter an integer number: 5
120


In [43]:
# Dictionary that contains (i, i*i) between 1 and n (both included) 
def generateDict ():
    controle= False 
    while(controle != True):
        try:
            n=int(input("Enter an integer number: "))
            numDict = {}
            for i in range(1, n+1):
                numDict[i]=i*i
            print( " The dictionary for this number is :")
            print(numDict)
            controle = True        
        except ValueError:
            print("Please input integer only...") 

In [44]:
generateDict()

Enter an integer number: 10
 The dictionary for this number is :
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [45]:
# function that return a new string where the char at index n has been removed

def removeChar(strCheck, pos ):
    if(strCheck == " "):
        print("String is empty !")
    else:
        if(pos > len(strCheck)-1):
            print(" Position out of range !")
        else:
            newStr=""
            for i in range (0, len(strCheck)):
                if(i != pos):
                    newStr=newStr+ strCheck[i] 
            return newStr  

In [47]:
removeChar("Douaa",4)

'Doua'

In [48]:
#convert a NumPy array into a Python list structure.
def convertNumArrayList (numPyArray):
    print("NumPyArray: ")
    print(type(numPyArray))
    print(numPyArray)
    lis= numPyArray.tolist()
    print("List: ")
    print(lis)
    print(type(lis))

In [49]:
import numpy as np 
arr = np.array([[0,1], [2, 3] ,[4 ,5]])
convertNumArrayList(arr)

NumPyArray: 
<class 'numpy.ndarray'>
[[0 1]
 [2 3]
 [4 5]]
List: 
[[0, 1], [2, 3], [4, 5]]
<class 'list'>


In [50]:
# NumPy program to compute the covariance matrix of two given arrays
def covArrays(array1,array2):
    # Original array1
    print(array1)
  
    # Original array2
    print(array2)
  
    # Covariance matrix
    print("\nCovariance matrix of the said arrays:\n",
    np.cov(array1, array2))
    

In [51]:
array1 = np.array([0,1,2])
array2= np.array([2,1,0])
covArrays(array1,array2)

[0 1 2]
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [52]:
# formula
import math as mt 
def formula ():
    Q= [ ]
    L = list(map(int, input("Enter multiple values\n").split(', ')))
    print("\nThe values of input are", L)
    C=50
    H=30
    for num in range (0, len(L)):
        Q.append(round(mt.sqrt(((2 * C * L[num])/H)))) 
    print(Q)

In [53]:
formula()

Enter multiple values
100, 150, 180

The values of input are [100, 150, 180]
[18, 22, 24]
